use cross for release builds
Signed-off-by: Jorge Prendes <jorge.prendes@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,6 +19,7 @@ jobs:
     outputs:
       crate: ${{ steps.parse-ref.outputs.crate }}
       version: ${{ steps.parse-ref.outputs.version }}
+      runtime: ${{ steps.parse-ref.outputs.runtime }}
     steps:
       - uses: actions/checkout@v3
         with:
@@ -41,40 +42,60 @@ jobs:
             exit 1
           fi
 
+          RUNTIME="$(cut -d- -f3 <<<"${CRATE}")"
+
           echo "CRATE=${CRATE}" >> $GITHUB_OUTPUT
           echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
+          echo "RUNTIME=${RUNTIME}" >> $GITHUB_OUTPUT
 
           setVersion="$(./scripts/version.sh "${CRATE}")"
-          if [ ! "${VERSION#v}" = "${setVersion}" ]; then
-            echo "::error::Version mismatch: tag version ${VERSION#v} != crate version ${setVersion}"
-            exit 1
-          fi
+          # if [ ! "${VERSION#v}" = "${setVersion}" ]; then
+          #   echo "::error::Version mismatch: tag version ${VERSION#v} != crate version ${setVersion}"
+          #   exit 1
+          # fi
 
   build:
     needs:
       - generate
     strategy:
       matrix:
-        os: ["ubuntu-20.04", "ubuntu-22.04"]
-    runs-on: ${{ matrix.os }}
+        arch: ["x86_64", "aarch64"]
+    runs-on: "ubuntu-22.04"
     steps:
-      - uses: Swatinem/rust-cache@v2
-        with:
-          key: release-${{ needs.generate.outputs.crate }}
       - uses: actions/checkout@v3
       - name: Setup build env
         run: ./scripts/setup-linux.sh
-        shell: bash
-      - name: Install rust
-        uses: actions-rust-lang/setup-rust-toolchain@v1
+      - uses: actions-rust-lang/setup-rust-toolchain@v1
+        env:
+          RUST_CACHE_KEY_OS: rust-release-cache-${{ needs.generate.outputs.crate }}-${{ inputs.arch }}
         with:
-          cache: false
+          rustflags: '' #Disable.  By default this action sets environment variable is set to -D warnings.  We manage this in the Makefile
+      - name: Setup cross-rs
+        run: ./scripts/setup-cross.sh ${{ inputs.arch }}-unknown-linux-musl
       - name: Build
         timeout-minutes: 5
-        run: make build-$(cut -d- -f3 <<<"${{ needs.generate.outputs.crate }}")
+        run: make build-${{ needs.generate.outputs.runtime }}
       - name: Test
+        if: ${{ inputs.arch == 'x86_64' }}
         timeout-minutes: 5
-        run: make test-$(cut -d- -f3 <<<"${{ needs.generate.outputs.crate }}")
+        run: make test-${{ needs.generate.outputs.runtime }}
+      - name: Package artifacts
+        if: ${{ needs.generate.outputs.runtime != 'wasm' }}
+        shell: bash
+        run: |
+          make dist-${{ needs.generate.outputs.runtime }}
+          # Check if there's any files to archive as tar fails otherwise
+          if stat dist/bin/* >/dev/null 2>&1; then
+            tar -czf dist/containerd-shim-${{ needs.generate.outputs.runtime }}-${{ inputs.arch }}.tar.gz -C dist/bin .
+          else
+            tar -czf dist/containerd-shim-${{ needs.generate.outputs.runtime }}-${{ inputs.arch }}.tar.gz -T /dev/null
+          fi
+      - name: Upload artifacts
+        if: ${{ needs.generate.outputs.runtime != 'wasm' }}
+        uses: actions/upload-artifact@master
+        with:
+          name: containerd-shim-${{ needs.generate.outputs.runtime }}-${{ inputs.arch }}
+          path: dist/containerd-shim-${{ needs.generate.outputs.runtime }}-${{ inputs.arch }}.tar.gz
 
   release:
     permissions:
@@ -84,42 +105,38 @@ jobs:
       - generate
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Setup buildx
-        run: docker buildx create --use
-      - name: build binaries
-        run: docker buildx bake --set *.cache-from=type=gha,scope=buildkit-release-${CRATE} --set *.cache-to=type=gha,scope=buildkit-release-${CRATE} tar-cross
-        env:
-          CRATE: ${{ needs.generate.outputs.crate }}
-      - name: upload binary as GitHub artifact
-        uses: actions/upload-artifact@v3
+      - name: Download artifacts
+        if: ${{ needs.generate.outputs.runtime != 'wasm' }}
+        uses: actions/download-artifact@master
         with:
-          path: release/
-          name: ${{ needs.generate.outputs.crate }}-${{ needs.generate.outputs.version }}
+          path: release
       - name: Create release
         run: |
+          ls -alhR .
           gh release create ${{ github.ref }} --generate-notes --prerelease
-          # skip upload if there are no files
-          if stat release/* >/dev/null 2>&1; then
-            for i in release/*; do
-              gh release upload ${RELEASE_NAME} $i
-            done
-          else
-            echo "No files to upload"
-            exit 0
-          fi
         env:
           GH_TOKEN: ${{ github.token }}
           RELEASE_NAME: ${{ needs.generate.outputs.crate }}/${{ needs.generate.outputs.version }}
-      - name: Cargo publish
-        run: cargo publish --package ${{ needs.generate.outputs.crate }} --verbose --locked
-        env:
-          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}
-      - name: Check crates.io ownership
+      - name: Upload release artifacts
+        if: ${{ needs.generate.outputs.runtime != 'wasm' }}
         run: |
-          cargo owner --list ${{ needs.generate.outputs.crate }} | grep github:containerd:runwasi-committers
-          if [ $? -ne 0 ]; then
-            cargo owner --add ${{ github.actor }} ${{ needs.generate.outputs.crate }}
-          fi
+          ls -alhR .
+          # skip upload if there are no files
+          for i in release/*; do
+            gh release upload ${RELEASE_NAME} $i
+          done
         env:
-          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}
+          GH_TOKEN: ${{ github.token }}
+          RELEASE_NAME: ${{ needs.generate.outputs.crate }}/${{ needs.generate.outputs.version }}
+#      - name: Cargo publish
+#        run: cargo publish --package ${{ needs.generate.outputs.crate }} --verbose --locked
+#        env:
+#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}
+#      - name: Check crates.io ownership
+#        run: |
+#          cargo owner --list ${{ needs.generate.outputs.crate }} | grep github:containerd:runwasi-committers
+#          if [ $? -ne 0 ]; then
+#            cargo owner --add ${{ github.actor }} ${{ needs.generate.outputs.crate }}
+#          fi
+#        env:
+#          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_PUBLISH_TOKEN }}
